USE [master]
GO
/****** Object:  Database [GroupAmitai]    Script Date: 1/2/2023 6:57:00 PM ******/
CREATE DATABASE [GroupAmitai]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GroupAmitai', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GroupAmitai.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GroupAmitai_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GroupAmitai_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GroupAmitai] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GroupAmitai].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GroupAmitai] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GroupAmitai] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GroupAmitai] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GroupAmitai] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GroupAmitai] SET ARITHABORT OFF 
GO
ALTER DATABASE [GroupAmitai] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GroupAmitai] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GroupAmitai] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GroupAmitai] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GroupAmitai] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GroupAmitai] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GroupAmitai] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GroupAmitai] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GroupAmitai] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GroupAmitai] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GroupAmitai] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GroupAmitai] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GroupAmitai] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GroupAmitai] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GroupAmitai] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GroupAmitai] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GroupAmitai] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GroupAmitai] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GroupAmitai] SET  MULTI_USER 
GO
ALTER DATABASE [GroupAmitai] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GroupAmitai] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GroupAmitai] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GroupAmitai] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GroupAmitai] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GroupAmitai] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GroupAmitai] SET QUERY_STORE = OFF
GO
USE [GroupAmitai]
GO
/****** Object:  Table [dbo].[Ingredients]    Script Date: 1/2/2023 6:57:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingredients](
	[ingredientsId] [int] IDENTITY(1,1) NOT NULL,
	[ingredientName] [nvarchar](50) NULL,
	[imgUrl] [nvarchar](500) NULL,
	[calories] [int] NULL,
 CONSTRAINT [PK_Ingredients] PRIMARY KEY CLUSTERED 
(
	[ingredientsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IngredientsInRecipes]    Script Date: 1/2/2023 6:57:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IngredientsInRecipes](
	[recipeId] [int] NOT NULL,
	[ingredientId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[recipeId] ASC,
	[ingredientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Recipes]    Script Date: 1/2/2023 6:57:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Recipes](
	[recipesId] [int] IDENTITY(1,1) NOT NULL,
	[recipesName] [nvarchar](50) NULL,
	[imageUrl] [nvarchar](500) NULL,
	[cookingMethod] [nvarchar](500) NULL,
	[time] [int] NULL,
 CONSTRAINT [PK_Recipes] PRIMARY KEY CLUSTERED 
(
	[recipesId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IngredientsInRecipes]  WITH CHECK ADD FOREIGN KEY([ingredientId])
REFERENCES [dbo].[Ingredients] ([ingredientsId])
GO
ALTER TABLE [dbo].[IngredientsInRecipes]  WITH CHECK ADD FOREIGN KEY([recipeId])
REFERENCES [dbo].[Recipes] ([recipesId])
GO
USE [master]
GO
ALTER DATABASE [GroupAmitai] SET  READ_WRITE 
GO
